/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clc;

/**
 *
 * @author Puma
 */
public class Master extends javax.swing.JFrame {

    /**
     * Creates new form Master
     */
    public Master() {
        initComponents();
    }
Aritmética arit = new Aritmética();
Trigonométrica trigo= new Trigonométrica();
Convertidora conver = new Convertidora();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto = new javax.swing.JTextField();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        bMultiplicar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        Sumar = new javax.swing.JButton();
        fc = new javax.swing.JButton();
        sen = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        kf = new javax.swing.JButton();
        kc = new javax.swing.JButton();
        ck = new javax.swing.JButton();
        cf = new javax.swing.JButton();
        temperatura = new javax.swing.JTextField();
        tan = new javax.swing.JButton();
        fk = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        mcm = new javax.swing.JButton();
        mmm = new javax.swing.JButton();
        min = new javax.swing.JButton();
        mft = new javax.swing.JButton();
        Medidas = new javax.swing.JTextField();
        cmmm = new javax.swing.JButton();
        cmm = new javax.swing.JButton();
        cmft = new javax.swing.JButton();
        cmin = new javax.swing.JButton();
        inft = new javax.swing.JButton();
        inm = new javax.swing.JButton();
        inmm = new javax.swing.JButton();
        incm = new javax.swing.JButton();
        ftcm = new javax.swing.JButton();
        ftm = new javax.swing.JButton();
        ftin = new javax.swing.JButton();
        ftmm = new javax.swing.JButton();
        kglb = new javax.swing.JButton();
        lbkg = new javax.swing.JButton();
        kgg = new javax.swing.JButton();
        gkg = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        Masa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        b4.setText("4");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });

        b1.setText("1");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        b8.setText("8");
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
        });

        b5.setText("5");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });

        b2.setText("2");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });

        b9.setText("9");
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
        });

        b6.setText("6");
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });

        b3.setText("3");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });

        Dividir.setText("/");
        Dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DividirMouseClicked(evt);
            }
        });

        bMultiplicar.setText("*");
        bMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMultiplicarMouseClicked(evt);
            }
        });

        Restar.setText("-");
        Restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarMouseClicked(evt);
            }
        });

        Sumar.setText("+");
        Sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarMouseClicked(evt);
            }
        });

        fc.setText("F° → C°");
        fc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fcMouseClicked(evt);
            }
        });

        sen.setText("sinRad");
        sen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senMouseClicked(evt);
            }
        });

        cos.setText("cosRad");
        cos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosMouseClicked(evt);
            }
        });

        kf.setText("K° →  F°");
        kf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kfMouseClicked(evt);
            }
        });

        kc.setText("K° → C°");
        kc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kcMouseClicked(evt);
            }
        });

        ck.setText("C° → K°");
        ck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckMouseClicked(evt);
            }
        });

        cf.setText("C° → F°");
        cf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cfMouseClicked(evt);
            }
        });

        tan.setText("tanRad");
        tan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanMouseClicked(evt);
            }
        });

        fk.setText("F° → K°");
        fk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fkMouseClicked(evt);
            }
        });

        b7.setText("7");
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });

        mcm.setText("m → cm");
        mcm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcmMouseClicked(evt);
            }
        });

        mmm.setText("m → mm");
        mmm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmmMouseClicked(evt);
            }
        });

        min.setText("m → in");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        mft.setText("m → ft");
        mft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mftMouseClicked(evt);
            }
        });

        cmmm.setText("cm → mm");
        cmmm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmmmMouseClicked(evt);
            }
        });

        cmm.setText("cm → m");
        cmm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmmMouseClicked(evt);
            }
        });

        cmft.setText("cm → ft");
        cmft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmftMouseClicked(evt);
            }
        });

        cmin.setText("cm → in");
        cmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cminMouseClicked(evt);
            }
        });

        inft.setText("in → ft");
        inft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inftMouseClicked(evt);
            }
        });

        inm.setText("in → m");
        inm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inmMouseClicked(evt);
            }
        });

        inmm.setText("in → mm");
        inmm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inmmMouseClicked(evt);
            }
        });

        incm.setText("in → cm");
        incm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incmMouseClicked(evt);
            }
        });

        ftcm.setText("ft → cm");
        ftcm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftcmMouseClicked(evt);
            }
        });

        ftm.setText("ft → m");
        ftm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftmMouseClicked(evt);
            }
        });

        ftin.setText("ft → in");
        ftin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftinMouseClicked(evt);
            }
        });

        ftmm.setText("ft → mm");
        ftmm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftmmMouseClicked(evt);
            }
        });

        kglb.setText("Kg → lb");
        kglb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kglbMouseClicked(evt);
            }
        });

        lbkg.setText("lb → Kg");
        lbkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbkgMouseClicked(evt);
            }
        });

        kgg.setText("Kg → g");
        kgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kggMouseClicked(evt);
            }
        });

        gkg.setText("g → Kg");
        gkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gkgMouseClicked(evt);
            }
        });

        igual.setText("=");
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
        });

        b0.setText("0");
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cos)
                                        .addGap(14, 14, 14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b0)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(igual))
                                    .addComponent(Sumar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b1)
                                    .addComponent(b4)
                                    .addComponent(b7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b2)
                                    .addComponent(b8)
                                    .addComponent(b5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b3)
                                    .addComponent(b9)
                                    .addComponent(b6))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bMultiplicar)
                                    .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cf)
                            .addComponent(ck)
                            .addComponent(kf)
                            .addComponent(kc)
                            .addComponent(fc)
                            .addComponent(fk)))
                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mmm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mft, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmmm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftmm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftcm, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(ftin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inft, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inmm)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kglb)
                        .addGap(18, 18, 18)
                        .addComponent(lbkg)
                        .addGap(28, 28, 28)
                        .addComponent(kgg)
                        .addGap(33, 33, 33)
                        .addComponent(gkg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Medidas, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Masa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(b4)
                                            .addGap(12, 12, 12)
                                            .addComponent(b1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(b9)
                                                .addComponent(Dividir))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(b6)
                                                .addComponent(bMultiplicar))
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(b3)
                                                .addComponent(Restar))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(b8)
                                            .addComponent(b7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b5)
                                        .addGap(12, 12, 12)
                                        .addComponent(b2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sumar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(igual))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b0)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sen)
                                            .addComponent(tan)
                                            .addComponent(cos)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Medidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(kf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kc)
                                .addGap(12, 12, 12)
                                .addComponent(ck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fk))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmm)
                                        .addComponent(ftm))
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmmm)
                                        .addComponent(ftcm))
                                    .addGap(7, 7, 7)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(inm)
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(inft)
                                    .addGap(7, 7, 7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mcm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mmm)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(min)
                                    .addComponent(cmin)
                                    .addComponent(ftmm)
                                    .addComponent(incm))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mft)
                                    .addComponent(cmft)
                                    .addComponent(ftin)
                                    .addComponent(inmm))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(Masa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kgg)
                                .addComponent(gkg))
                            .addComponent(lbkg)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(kglb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
      Texto.setText(Texto.getText() + "1");
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
      Texto.setText(Texto.getText()+"2");        // TODO add your handling code here:
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
      Texto.setText(Texto.getText()+"3");        // TODO add your handling code here:
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
      Texto.setText(Texto.getText()+"4");        // TODO add your handling code here:
    }//GEN-LAST:event_b4MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
      Texto.setText(Texto.getText()+"8");        // TODO add your handling code here:
    }//GEN-LAST:event_b8MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
      Texto.setText(Texto.getText()+"5");        // TODO add your handling code here:
    }//GEN-LAST:event_b5MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
      Texto.setText(Texto.getText()+"9");        // TODO add your handling code here:
    }//GEN-LAST:event_b9MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
      Texto.setText(Texto.getText()+"6");        // TODO add your handling code here:
    }//GEN-LAST:event_b6MouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
 double valor2 = Double.parseDouble(Texto.getText());
    arit.operando2 = valor2;
   
    switch(arit.operando){
            case "+":                
                String rest = String.valueOf(arit.suma());                
                Texto.setText(rest);
                break;
                
            case "-":
                String rest2 = String.valueOf(arit.resta()); 
                Texto.setText(rest2);                
                break;
                  case "*":
                String rest3 = String.valueOf(arit.multiplicacion()); 
                Texto.setText(rest3);                
                break;
                  case "/":
                String rest4 = String.valueOf(arit.division()); 
                Texto.setText(rest4);                
                break;
                
            default:
                    break;
    }
   
          // TODO add your handling code here:
    }//GEN-LAST:event_igualMouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
     Texto.setText(Texto.getText()+"7");   // TODO add your handling code here:
    }//GEN-LAST:event_b7MouseClicked

    private void b0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseClicked
        Texto.setText(Texto.getText()+"0");// TODO add your handling code here:
    }//GEN-LAST:event_b0MouseClicked

    private void SumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarMouseClicked
       double valor = Double.parseDouble(Texto.getText());
    arit.operando1 = valor;
    Texto.setText(" ");
    arit.operando = "+";
    }//GEN-LAST:event_SumarMouseClicked

    private void RestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarMouseClicked
 double valor = Double.parseDouble(Texto.getText());
    arit.operando1 = valor;
    Texto.setText(" ");
    arit.operando = "-";        // TODO add your handling code here:
    }//GEN-LAST:event_RestarMouseClicked

    private void bMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMultiplicarMouseClicked
     double valor = Double.parseDouble(Texto.getText());
    arit.operando1 = valor;
    Texto.setText(" ");
    arit.operando = "*";   // TODO add your handling code here:
    }//GEN-LAST:event_bMultiplicarMouseClicked

    private void DividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DividirMouseClicked
 double valor = Double.parseDouble(Texto.getText());
    arit.operando1 = valor;
    Texto.setText(" ");
    arit.operando = "/";        // TODO add your handling code here:
    }//GEN-LAST:event_DividirMouseClicked

    private void senMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senMouseClicked
      double sin = Double.parseDouble(Texto.getText());
      
      trigo.ang = sin;
      double x = trigo.seno();
      String x1 = String.valueOf(x);
      Texto.setText(x1);
    }//GEN-LAST:event_senMouseClicked

    private void cosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosMouseClicked
        double coss = Double.parseDouble(Texto.getText());
        trigo.ang = coss;
      double x = trigo.coseno();
      String x1 = String.valueOf(x);
      Texto.setText(x1);
    }//GEN-LAST:event_cosMouseClicked

    private void tanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanMouseClicked
        double tann = Double.parseDouble(Texto.getText());
        trigo.ang = tann;
      double x = trigo.coseno();
      String x1 = String.valueOf(x);
      Texto.setText(x1);
    }//GEN-LAST:event_tanMouseClicked

    private void kfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kfMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertKelvinToFahrenh();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_kfMouseClicked

    private void kcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kcMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertKelvinToCelcius();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_kcMouseClicked

    private void ckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertCelciusToKelvin();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_ckMouseClicked

    private void cfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cfMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.covertCelciusToFahrenh();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_cfMouseClicked

    private void fcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertFahrenhToCelcius();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_fcMouseClicked

    private void fkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertFahrenhToKelvin();
     String t = String.valueOf(z);
     temperatura.setText(t);
    }//GEN-LAST:event_fkMouseClicked

    private void mcmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcmMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertMetrosToCentimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_mcmMouseClicked

    private void mmmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmmMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertMetrosToMilimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_mmmMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
  double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertMetrosToPulgada();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_minMouseClicked

    private void mftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mftMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertMetrosToPie();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_mftMouseClicked

    private void cmmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmmMouseClicked
       double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertCentimetrosToMetros();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_cmmMouseClicked

    private void cmmmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmmmMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertCentimetrosToMilimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_cmmmMouseClicked

    private void cminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cminMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertCentimetrosToPulgada();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_cminMouseClicked

    private void cmftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmftMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertCentimetrosToPie();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_cmftMouseClicked

    private void inmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inmMouseClicked
    double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPulgadaToMetros();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_inmMouseClicked

    private void ftcmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftcmMouseClicked
     double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPieToCentimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);
    }//GEN-LAST:event_ftcmMouseClicked

    private void ftmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftmMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPieToMetros();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_ftmMouseClicked

    private void ftmmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftmmMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPieToMilimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_ftmmMouseClicked

    private void inftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inftMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPulgadaToPie();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_inftMouseClicked

    private void incmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incmMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPulgadaToCentimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_incmMouseClicked

    private void inmmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inmmMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPulgadaToMilimetros();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_inmmMouseClicked

    private void ftinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftinMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertPieToPulgada();
     String t = String.valueOf(z);
     Medidas.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_ftinMouseClicked

    private void kglbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kglbMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertKgToLb();
     String t = String.valueOf(z);
     Masa.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_kglbMouseClicked

    private void lbkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbkgMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertLbtoKg();
     String t = String.valueOf(z);
     Masa.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_lbkgMouseClicked

    private void kggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kggMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertKgToGramos();
     String t = String.valueOf(z);
     Masa.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_kggMouseClicked

    private void gkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gkgMouseClicked
double k = Double.parseDouble(Texto.getText());
     conver.numero = k;
     double z =conver.convertGramosToKg();
     String t = String.valueOf(z);
     Masa.setText(t);        // TODO add your handling code here:
    }//GEN-LAST:event_gkgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dividir;
    private javax.swing.JTextField Masa;
    private javax.swing.JTextField Medidas;
    private javax.swing.JButton Restar;
    private javax.swing.JButton Sumar;
    private javax.swing.JTextField Texto;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bMultiplicar;
    private javax.swing.JButton cf;
    private javax.swing.JButton ck;
    private javax.swing.JButton cmft;
    private javax.swing.JButton cmin;
    private javax.swing.JButton cmm;
    private javax.swing.JButton cmmm;
    private javax.swing.JButton cos;
    private javax.swing.JButton fc;
    private javax.swing.JButton fk;
    private javax.swing.JButton ftcm;
    private javax.swing.JButton ftin;
    private javax.swing.JButton ftm;
    private javax.swing.JButton ftmm;
    private javax.swing.JButton gkg;
    private javax.swing.JButton igual;
    private javax.swing.JButton incm;
    private javax.swing.JButton inft;
    private javax.swing.JButton inm;
    private javax.swing.JButton inmm;
    private javax.swing.JButton kc;
    private javax.swing.JButton kf;
    private javax.swing.JButton kgg;
    private javax.swing.JButton kglb;
    private javax.swing.JButton lbkg;
    private javax.swing.JButton mcm;
    private javax.swing.JButton mft;
    private javax.swing.JButton min;
    private javax.swing.JButton mmm;
    private javax.swing.JButton sen;
    private javax.swing.JButton tan;
    private javax.swing.JTextField temperatura;
    // End of variables declaration//GEN-END:variables
}
